data_arguments:
  seed: 1314
  data_dir: "../../../datasets/conll"
  data_type: conll
  labels: "../../../datasets/conll/biaffine_labels.txt"
  ignore_index: -100
  sub_token_label_scheme: v1
  overwrite_cache: false


train_argunents:
  task_name: conll
  model_type: bertbiaffine
  model_name_or_path: "bert-base-uncased"
  learning_rate: 0.00002
  classifiers_learning_rate: 0.0001
  num_train_epochs: 20
  warmup_steps: 32
  evaluate_during_training: true
  per_gpu_train_batch_size: 128
  per_gpu_eval_batch_size: 64
  max_seq_length: 128
  do_lower_case: true
  eval_all_checkpoints: true
  gradient_checkpointing: true
  is_flat_ner: false
  simplify_biaffine: false
  sampling_ratio: 0.9
  do_hard_negative_sampling: false
  hns_multiplier: 0.3
  use_lstm: false
  use_ffn: false
  use_focal: false



output_arguments:
  output_dir: "../../../experiments/outputs"
  logging_steps: 50
  save_steps: 50
  log_dir: "../../../experiments/logs"
  tensorboardx_path: "../../../experiments/runs"
  overwrite_output_dir: true
  file_to_predict: false