data_arguments:
  seed: 1314
  data_dir: "../../../datasets/conll"
  data_type: conll
  labels: "../../../datasets/conll/globalpointer_labels.txt"
  ignore_index: -100
  sub_token_label_scheme: v1
  overwrite_cache: true


train_argunents:
  task_name: conll
  model_type: bertglobalpointer
  model_name_or_path: "bert-base-uncased"
  learning_rate: 0.00002
  global_pointer_learning_rate: 0.0001
  num_train_epochs: 20
  warmup_steps: 32
  is_flat_ner: false
  evaluate_during_training: true
  per_gpu_train_batch_size: 128
  per_gpu_eval_batch_size: 64
  max_seq_length: 128
  do_lower_case: true
  eval_all_checkpoints: true
  gradient_checkpointing: true
  use_RoPE: true

output_arguments:
  output_dir: "../../../experiments/outputs"
  logging_steps: 50
  save_steps: 50
  log_dir: "../../../experiments/logs"
  tensorboardx_path: "../../../experiments/runs"
  overwrite_output_dir: true