data_arguments:
  seed: 1314
  data_dir: "../../../datasets/conll"
  data_type: conll
  labels: "../../../datasets/conll/bilstm_labels.txt"
  vocab_dir: "../../../datasets/conll/vocab.txt"
  ignore_index: 0
  sub_token_label_scheme: v1
  overwrite_cache: false
  unk_token: "[UNK]"
  pad_token: "[PAD]"
  pad_token_label_id: 0
  random_init_w2v: true


train_argunents:
  task_name: conll
  model_type: bilstm
  embed_dim: 200
  hidden_dim: 100
  classifier_learning_rate: 0.002
  embeddings_learning_rate: 0.0006
  crf_learning_rate: 0.0001
  lstm_learning_rate: 0.002
  num_train_epochs: 20
  warmup_steps: 32
  evaluate_during_training: true
  per_gpu_train_batch_size: 128
  per_gpu_eval_batch_size: 64
  max_seq_length: 128
  do_lower_case: false
  eval_all_checkpoints: true
  gradient_checkpointing: true
  use_crf: false

output_arguments:
  output_dir: "../../../experiments/outputs"
  logging_steps: 50
  save_steps: 50
  log_dir: "../../../experiments/logs"
  tensorboardx_path: "../../../experiments/runs"
  overwrite_output_dir: true